# Generated by Django 5.1.7 on 2025-03-14 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_libro', models.CharField(max_length=50)),
                ('autor', models.CharField(max_length=50)),
                ('editorial', models.CharField(max_length=50)),
                ('edicion', models.CharField(max_length=50)),
                ('año', models.CharField(max_length=7)),
                ('isbn', models.CharField(max_length=50)),
                ('valor_saberes', models.BigIntegerField()),
            ],
        ),
    ]
