# Generated by Django 5.1.7 on 2025-07-03 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='saber',
            field=models.IntegerField(default=0),
        ),
    ]
