# Generated by Django 5.1.7 on 2025-07-03 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_perfil_saber'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='favoritos',
            field=models.ManyToManyField(blank=True, related_name='usuarios_favoritos', to='catalogo.libro'),
        ),
    ]
